#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-jupytext
Version  : 1.15.1
Release  : 27
URL      : https://files.pythonhosted.org/packages/a1/89/197faaa454f041dea5e96d5073e42a981ad42d9352aec191894341d69f54/jupytext-1.15.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a1/89/197faaa454f041dea5e96d5073e42a981ad42d9352aec191894341d69f54/jupytext-1.15.1.tar.gz
Summary  : Jupyter notebooks as Markdown documents, Julia, Python or R scripts
Group    : Development/Tools
License  : MIT
Requires: pypi-jupytext-bin = %{version}-%{release}
Requires: pypi-jupytext-data = %{version}-%{release}
Requires: pypi-jupytext-license = %{version}-%{release}
Requires: pypi-jupytext-python = %{version}-%{release}
Requires: pypi-jupytext-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jupyter_packaging)
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(markdown_it_py)
BuildRequires : pypi(mdit_py_plugins)
BuildRequires : pypi(nbformat)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(toml)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
![](https://github.com/mwouts/jupytext/blob/17aea37c612f33a4e27eeee4b81966f1506920fd/docs/images/logo_large.png?raw=true)

%package bin
Summary: bin components for the pypi-jupytext package.
Group: Binaries
Requires: pypi-jupytext-data = %{version}-%{release}
Requires: pypi-jupytext-license = %{version}-%{release}

%description bin
bin components for the pypi-jupytext package.


%package data
Summary: data components for the pypi-jupytext package.
Group: Data

%description data
data components for the pypi-jupytext package.


%package license
Summary: license components for the pypi-jupytext package.
Group: Default

%description license
license components for the pypi-jupytext package.


%package python
Summary: python components for the pypi-jupytext package.
Group: Default
Requires: pypi-jupytext-python3 = %{version}-%{release}

%description python
python components for the pypi-jupytext package.


%package python3
Summary: python3 components for the pypi-jupytext package.
Group: Default
Requires: python3-core
Provides: pypi(jupytext)
Requires: pypi(markdown_it_py)
Requires: pypi(mdit_py_plugins)
Requires: pypi(nbformat)
Requires: pypi(pyyaml)
Requires: pypi(toml)

%description python3
python3 components for the pypi-jupytext package.


%prep
%setup -q -n jupytext-1.15.1
cd %{_builddir}/jupytext-1.15.1
pushd ..
cp -a jupytext-1.15.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693252012
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jupytext
cp %{_builddir}/jupytext-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupytext/f5b82cb3f91043792b01d28bb7c8db01fa8d6de5 || :
cp %{_builddir}/jupytext-%{version}/packages/labextension/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupytext/6070800810da89afd1bfd1d32e40f9cb79531c0e || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
pypi-dep-fix.py %{buildroot} markdown-it-py
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_notebook_config.d/jupytext.json
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/jupytext.json
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/notebook.d/jupytext.json
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupytext
/usr/bin/jupytext-config

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/nbextensions/jupytext/README.md
/usr/share/jupyter/nbextensions/jupytext/index.js
/usr/share/jupyter/nbextensions/jupytext/jupytext.yml
/usr/share/jupyter/nbextensions/jupytext/jupytext_menu.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jupytext/6070800810da89afd1bfd1d32e40f9cb79531c0e
/usr/share/package-licenses/pypi-jupytext/f5b82cb3f91043792b01d28bb7c8db01fa8d6de5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
